In [5]:
# Import numpy
import numpy as np

**1. Write a function so that the columns of the output matrix are powers of the input
vector.**<br>
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [106]:
def output(lst, k):
    a = np.vander(lst, k, increasing = False)
    print(a)

In [109]:
l = list(map(int, input("> Enter comma seperated numbers for vector..").split(',')))
k = int(input("> Enter no.of columns..."))

> Enter comma seperated numbers for vector..1,2,3,4,5,6
> Enter no.of columns...5


In [110]:
output(l, k)

[[   1    1    1    1    1]
 [  16    8    4    2    1]
 [  81   27    9    3    1]
 [ 256   64   16    4    1]
 [ 625  125   25    5    1]
 [1296  216   36    6    1]]


**2. Write a function to find moving average in an array over a window:**<br>

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [51]:
def moving_avg(lst, k):
    print("Array = ",lst)
    print('Window size = ',k)
    for i in range(len(lst)-k+1):
        avg = np.sum(lst[i:i+k])/k
        print('Moving average {} = {}'.format(i+1, avg))
        

In [52]:
l = list(map(int, input("> Enter comma seperated numbers for array..").split(',')))
k = int(input("> Enter Window size..."))

> Enter comma seperated numbers for array..3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150
> Enter Window size...3


In [49]:
moving_avg(np.array(l), k)

Array =  [ 1  2  3  4  5  6  7  8  9 10]
Window size =  4
Moving average 1 = 2.5
Moving average 2 = 3.5
Moving average 3 = 4.5
Moving average 4 = 5.5
Moving average 5 = 6.5
Moving average 6 = 7.5
Moving average 7 = 8.5


In [53]:
moving_avg(np.array(l), k)

Array =  [  3   5   7   2   8  10  11  65  72  81  99 100 150]
Window size =  3
Moving average 1 = 5.0
Moving average 2 = 4.666666666666667
Moving average 3 = 5.666666666666667
Moving average 4 = 6.666666666666667
Moving average 5 = 9.666666666666666
Moving average 6 = 28.666666666666668
Moving average 7 = 49.333333333333336
Moving average 8 = 72.66666666666667
Moving average 9 = 84.0
Moving average 10 = 93.33333333333333
Moving average 11 = 116.33333333333333
